version: '3.8'

services:
  web:
    build: .
    container_name: carnet_sena_web
    restart: always
    ports:
      - "5000:5000"
    volumes:
      # Montamos la carpeta instance para no perder la base de datos SQLite
      - ./carnet-sena/instance:/app/instance
      # Montamos la carpeta de uploads para no perder las imágenes o códigos QR generados
      - ./carnet-sena/app/static/uploads:/app/app/static/uploads
    env_file:
      - ./carnet-sena/.env
    environment:
      - TZ=America/Bogota
